version: "3.1"

services:
    db:
        image: postgres:12.5
        command: postgres -c 'max_connections=1000'
        restart: always
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: mydbuser
            POSTGRES_PASSWORD: mydbpwd
        ports:
            - "5435:5432"
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
        depends_on:
            - db
    mailhog:
        image: mailhog/mailhog:latest
        restart: always
        ports:
            - 1025:1025
            - 8025:8025