version: 0.2

env:
    variables:
        TF_VERSION: 0.14.6

phases:
    install:
        runtime-versions:
            nodejs: 14.x
        commands:
            - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
            - apt-get -y update
            - curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
            - unzip terraform.zip
            - mv terraform /usr/bin
            - npm install -g serverless@2.62.0

    build:
        commands:
            # Terraform
            - echo "terraform build"
            - cd $CODEBUILD_SRC_DIR/infra/create-app
            - terraform init
            - terraform workspace select $STAGE || terraform workspace new $STAGE
            - terraform apply --var-file=$STAGE.tfvars -input=false -auto-approve
            # API
            - cd $CODEBUILD_SRC_DIR/api
            - npm install
            - serverless create_domain --stage $STAGE
            - sls deploy --stage $STAGE
            # Migrations and seeds
            # - SLS_DEBUG=* serverless invoke --function migrate --stage $STAGE --region=eu-west-1 # this is using knex migration function invoking, y/n?
            # UI - What do we want to do here for next, yikes? - some docker stuff here i guess
            # - cd $CODEBUILD_SRC_DIR/ui
            # - npm install
            # - REACT_APP_ENV=$STAGE npm run build
            # - cd $CODEBUILD_SRC_DIR/ui/build
            # - aws s3 sync . s3://fe-elevator-ui-$STAGE
