service: octopus-api

plugins:
    - serverless-plugin-warmup
    - serverless-middleware
    - serverless-domain-manager
    - serverless-webpack
    - serverless-offline
    - serverless-pseudo-parameters

provider:
    name: aws
    timeout: 30
    runtime: nodejs14.x
    region: eu-west-1
    stage: ${opt:stage, 'local'}
    vpc:
        securityGroupIds:
            - ${ssm:/${self:provider.stage}_octopus_sls_sg}
        subnetIds:
            - ${ssm:/${self:provider.stage}_octopus_private_subnet_az1}
            - ${ssm:/${self:provider.stage}_octopus_private_subnet_az2}
            - ${ssm:/${self:provider.stage}_octopus_private_subnet_az3}
    environment:
        stage: ${self:provider.stage}
    deploymentBucket:
        tags:
            Project: Octopus
            Owner: 0 - 3 Years Innovation Team
            Name: Octopus API
custom:
    webpack:
        webpackConfig: ./webpack.config.js
        includeModules: true
        packager: 'npm'
    versions:
        v1: v1
    serverless-offline:
        useChildProcesses: true
functions:
    healthcheck:
        handler: src/components/application/routes.healthcheck
        warmup: true
        events:
            - http:
                  path: ${self:custom.versions.v1}/healthcheck
                  method: get
                  cors: true
    getPublications:
        handler: src/components/publication/routes.getAll
        warmup: true
        events:
            - http:
                  path: ${self:custom.versions.v1}/publications
                  method: get
                  cors: true
    getPublication:
        handler: src/components/publication/routes.get
        warmup: true
        events:
            - http:
                  path: ${self:custom.versions.v1}/publications/{id}
                  method: get
                  cors: true
    createPublication:
        handler: src/components/publication/routes.create
        warmup: true
        events:
            - http:
                  path: ${self:custom.versions.v1}/publications
                  method: post
                  cors: true
    createLink:
        handler: src/components/link/routes.create
        warmup: true
        events:
            - http:
                  path: ${self:custom.versions.v1}/links
                  method: post
                  cors: true
    updateStatus:
        handler: src/components/publication/routes.updateStatus
        warmup: true
        events:
            - http:
                  path: ${self:custom.versions.v1}/publications/{id}/status/{status}
                  method: put
                  cors: true
    updatePublication:
        handler: src/components/publication/routes.update
        warmup: true
        events:
            - http:
                  path: ${self:custom.versions.v1}/publications/{id}
                  method: patch
                  cors: true
    getUsers:
        handler: src/components/user/routes.getAll
        warmup: true
        events:
            - http:
                  path: ${self:custom.versions.v1}/users
                  method: get
                  cors: true
    getUser:
        handler: src/components/user/routes.get
        warmup: true
        events:
            - http:
                  path: ${self:custom.versions.v1}/users/{id}
                  method: get
                  cors: true
    createFlag:
        handler: src/components/publication/routes.createFlag
        warmup: true
        events:
            - http:
                  path: ${self:custom.versions.v1}/publications/{id}/flag
                  method: post
                  cors: true
