service: octopus

plugins:
  - serverless-plugin-warmup
  - serverless-middleware
  - serverless-domain-manager
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  stage: ${opt:stage, 'local'}
  environment:
    stage: ${self:provider.stage}
  deploymentBucket:
    tags:
      Project: Jisc SSO
      Owner: 0 - 3 Years Innovation Team
      Name: Jisc SSO API
